version: '3'
      
services:

  postgres:
    build:
      context: ./forDatabaseDeploy
      dockerfile: Dockerfile
    ports:
      - "5432:5432"

  go:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      - DATABASE_IP=postgres
